### ISSUE TITLE
Failed to load module script

### ISSUE THREAD

**Issue by guguji5** [systemjs/systemjs-examples#12]
Hi @joeldenning, last night I see your [video](https://www.bilibili.com/video/av83620028) about the systemjs. I try your code in your sample, but get the error as below:

`
Failed to load module script: The server responded with a non-JavaScript MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.
`

I run a simple html in my nginx server. 

```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>single-spa MIS</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">

  </head>
  <body>
    <div class="wrapper">
      <div id="content">
        Today, our topic is {{topic}}
      </div>
    </div>
    
    <script type="module">
      import Vue from "https://unpkg.com/browse/vue@2.6.11/dist/vue.esm.browser.min.js"

      new Vue({
        el:"content",
        data:{
          topic:"systemJs"
        }
      })
    </script>

  </body>
</html>
```

Could you help me with it? 

By the way, my computer is mac, and the browser is chrome with version  80.0.3987.116.

**Comment by internettrans** [comment]
https://unpkg.com/browse/vue@2.6.11/dist/vue.esm.browser.min.js is the unpkg html file for Vue. It's not a js file. Change it to https://unpkg.com/vue@2.6.11/dist/vue.esm.browser.min.js.

Also, your  code isn't using systemjs at all. Which is okay, but just thought I'd point it out. Closing this issue since I think I've identified the problem. Feel free to comment further or reopen.
